inputs:
  machine:
    default: 'raspberrypi5'
  target:
    default: 'core-image-weston-wpe'
  github_token:
    required: true
  s3_storage:
    required: true
  wpe_version:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Print environment
      shell: bash
      run:  |
        echo "Environment:"
        echo "======================================================================"
        echo "MACHINE=${{ inputs.machine }}"
        echo "S3_STORAGE=${{ inputs.s3_storage }}"
        echo "TARGET=${{ inputs.target }}"
        echo "WPE_VERSION=${{ inputs.wpe_version }}"
        echo "======================================================================"
    - name: Download timestamp artifact
      uses: actions/download-artifact@v4
      with:
        pattern: timestamp.txt
        merge-multiple: true
    - name: Get timestamped prefix
      id: timestamp
      shell: bash
      run: |
        TIMESTAMP=$(cat timestamp.txt)
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
    - name: Prepare the Robot-Framework related PODs in background
      shell: bash
      run:  |
        git lfs pull
        pushd .ci
        podman rm ci_webserver_1 ci_robot_1 -f
        ./podman-compose.sh up --force-recreate --always-recreate-deps --build -d
        popd
    - name: Flash
      shell: bash
      run:  |
        TIMESTAMP=${{ steps.timestamp.outputs.timestamp }}
        s3cmd get -F s3://${{ inputs.s3_storage }}/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.wic.bmap
        s3cmd get -F s3://${{ inputs.s3_storage }}/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.wic.bz2
        sudo flash ${{ inputs.target }} ${{ inputs.machine }}
    - name: Test
      shell: bash
      run:  |
        TIMESTAMP=${{ steps.timestamp.outputs.timestamp }}
        GITHUB_PR_SHA=${GITHUB_SHA}
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            GITHUB_PR_SHA=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)
        fi
        cd .ci
        echo "ðŸ’¿ï¸ **Image for [wpe-${{ inputs.wpe_version }}-${{ inputs.machine }](https://wk-contrib.igalia.com/yocto/meta-wpe-image/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }/) (ref: ${GITHUB_PR_SHA}).**" > ci-message.txt
        IP=$(sudo manage-devices -c /etc/manage-devices.yml ip ${{ inputs.machine }})
        WEBSERVER_IP=$(ip -4 addr show eno1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
        echo "#!/bin/sh" > setup-env-local.sh
        echo "export TEST_BOARD_IP=${IP}" >> setup-env-local.sh
        echo "export TEST_WEBSERVER_IP=${WEBSERVER_IP}" >> setup-env-local.sh
        echo "export TEST_WPEWEBKIT_VERSION=${{ inputs.wpe_version }}" >> setup-env-local.sh
        echo "export TEST_MACHINE=${{ inputs.machine }}" >> setup-env-local.sh
        if ./run-tests.sh; then
          MESSAGE="Tests results: https://wk-contrib.igalia.com/yocto/meta-wpe-image/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }/robot/report.html - Tests passed for \`wpe-${{ inputs.wpe_version }}-${{ inputs.machine }\` on \`${{ inputs.target }}\`."
          echo "::notice file=.ci/run-tests.sh,title=Robot Framework tests::${MESSAGE}"
          echo "* âœ…ï¸ ${MESSAGE}" >> ci-message.txt
        else
          MESSAGE="Tests results: https://wk-contrib.igalia.com/yocto/meta-wpe-image/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }/robot/report.html - Failures were detected in the test results for \`wpe-${{ inputs.wpe_version }}-${{ inputs.machine }\` on \`${{ inputs.target }}\`."
          echo "::warning file=.ci/run-tests.sh,title=Robot Framework tests::${MESSAGE}"
          echo "* âš ï¸  ${MESSAGE}" >> ci-message.txt
        fi
        s3cmd put -r -F tests_results/robot s3://${{ inputs.s3_storage }}/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }/
    - name: Comment on the pull request
      uses: mshick/add-pr-comment@v2
      with:
        message-id: wpe-${{ inputs.wpe_version }}-${{ inputs.machine }-${{ steps.timestamp.outputs.timestamp }}
        message-path: |
            .ci/ci-message.txt
    - name: Stop DUT and Clean the tests directory
      if: always()
      shell: bash
      run:  |
        sudo manage-devices -c /etc/manage-devices.yml down ${{ inputs.machine }}
        rm -rf .ci/setup-env-local.sh .ci/tests_results .ci/ci-message.txt
