inputs:
  machine:
    default: 'raspberrypi5'
  presets_extra:
    default: ''
  repo_release:
    default: 'scarthgap'
  s3_storage:
    required: true
  target:
    default: 'core-image-weston-wpe'
  wpe_version:
    default: 'nightly'

runs:
  using: 'composite'
  steps:
    - name: Print environment
      shell: bash
      run:  |
        echo "Environment:"
        echo "======================================================================"
        echo "MACHINE=${{ inputs.machine }}"
        echo "PRESETS_EXTRA=${{ inputs.presets_extra }}"
        echo "RELEASE=${{ inputs.repo_release }}"
        echo "TARGET=${{ inputs.target }}"
        echo "WPE_VERSION=${{ inputs.wpe_version }}"
        echo "======================================================================"
    - name: Download timestamp artifact
      uses: actions/download-artifact@v4
      with:
        pattern: timestamp.txt
        merge-multiple: true
    - name: Get timestamp prefix
      id: timestamp
      shell: bash
      run: |
        TIMESTAMP=$(cat timestamp.txt)
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
    - name: Clean the build dir
      shell: bash
      run:  |
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}.tar
    - name: Download workdir artifact
      uses: actions/download-artifact@v4
      with:
        name: yocto-meta-wpe-image-${{ inputs.repo_release }}-${{ inputs.machine }}-${{ inputs.wpe_version }}
        path:  ~/
    - name: Untar workdir
      shell: bash
      run:  |
        cd ~
        tar -xf yocto-meta-wpe-image-${{ inputs.repo_release }}.tar
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}.tar
    - name: Build
      shell: bash
      run:  |
        export KAS_WORK_DIR="workdir"

        # requires: sudo apt-get install -y git git-lfs pip
        #           pip/pipx install kas
        export PATH=$PATH:~/.local/bin

        cd ~/yocto-meta-wpe-image-${{ inputs.repo_release }}
        cp /kas-local.yml ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/

        ulimit -n 4096
        MAX_RETRIES=5
        for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i to fetch sources for $IMAGE..."
           if kas shell kas.yml:kas/machines/${{ inputs.machine }}.yml:kas/presets/wpe-${{ inputs.wpe_version }}.yml:kas-local.yml -c "bitbake ${{ inputs.target }} --runall=fetch"; then
                echo "All sources fetched successfully."
                break
            fi

            if [ $i -lt $MAX_RETRIES ]; then
                echo "Retrying fetch process..."
            else
                echo "Max retries reached. Some sources may still be missing."
            fi
        done

        kas build kas.yml:kas/machines/${{ inputs.machine }}.yml:kas/presets/wpe-${{ inputs.wpe_version }}.yml${{ inputs.presets_extra}}:kas-local.yml
    - name: Artifacts
      if: always()
      shell: bash
      run: |
        ls -lh ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/${KAS_WORK_DIR}/build/tmp/deploy/images/${{ inputs.machine }}/
        TIMESTAMP=${{ steps.timestamp.outputs.timestamp }}
        s3cmd put -F ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/${KAS_WORK_DIR}/build/tmp/deploy/images/${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.rootfs.wic.bmap \
            s3://${{ inputs.s3_storage }}/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.wic.bmap
        s3cmd put -F ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/${KAS_WORK_DIR}/build/tmp/deploy/images/${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.rootfs.wic.bz2 \
            s3://${{ inputs.s3_storage }}/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.wic.bz2
        s3cmd put -F ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/${KAS_WORK_DIR}/build/tmp/deploy/images/${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.rootfs.dbg.tar.bz2 \
            s3://${{ inputs.s3_storage }}/${TIMESTAMP}-wpe-${{ inputs.wpe_version }}-${{ inputs.machine }}/${{ inputs.target }}-${{ inputs.machine }}.dbg.tar.bz2
    - name: Clean the tmp dir
      if: always()
      shell: bash
      run:  |
        # rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}
