#! /bin/bash

set -e

scripts=$(find . -executable -type f ! -path '*/\.*' -exec grep -lE '^#! *(|/usr/bin/env +|/bin/|/usr/bin/)(python|python3)' {} +)
echo "Running pyflakes3 on the following scripts:"
echo "$scripts"
errors=0
for script in $scripts; do
  if ! pyflakes3 "$script"; then
    errors=$((errors + 1))
  fi
done
if [ "$errors" -ne 0 ]; then
  echo "pyflakes3 found issues."
  exit 1
fi
echo "pyflakes3 passed successfully."
