require conf/distro/moonforge.conf

DISTRO = "demos"
DISTRO_NAME = "Igalia Demos Distro based on Moonforge Linux"
DISTRO_VERSION = "2.0"

MAINTAINER = "Pablo Saavedra <psaavedra@igalia.com>"

DISTRO_FEATURES:remove = "ptest"

# Vulkan stack (vulkan-loader/mesa-vulkan-drivers gate on this via features_check)
DISTRO_FEATURES:append = " vulkan"

# GStreamer Video decoder v4l2h264dec (by default):
PACKAGECONFIG:append:pn-gstreamer1.0-plugins-bad = " v4l2codecs"

PACKAGECONFIG:append:pn-qemu-native = " sdl"
PACKAGECONFIG:append:pn-nativesdk-qemu = " sdl"

# SDK / toolchain extras (centralized here from image_demos.bbclass)
SDK_EXTRA_TOOLS += "nativesdk-cmake nativesdk-ninja \
    nativesdk-perl-module-findbin \
    nativesdk-perl-misc \
    nativesdk-gperf \
    nativesdk-unifdef \
    "

TOOLCHAIN_HOST_TASK:append = " ${SDK_EXTRA_TOOLS}"
TOOLCHAIN_TARGET_TASK:append = " openjpeg-staticdev"
TOOLCHAIN_TARGET_TASK:append = " libjxl"
TOOLCHAIN_TARGET_TASK:remove = "target-sdk-provides-dummy"

