# Distro based on Moonforge
require conf/distro/moonforge-wayland.conf

DISTRO = "wpe"
DISTRO_NAME = "WPE Wayland Distribution"
DISTRO_VERSION = "2.0"
DISTRO_CODENAME = "wpe"

MAINTAINER = "Pablo Saavedra <psaavedra@igalia.com>"

