inputs:
  bitbake_buildname:
    default: 'build'
  bitbake_prefix:
    default: ''
  bitbake_machine:
    default: 'raspberrypi5'
  bitbake_target:
    default: 'core-image-weston-wpe'
  bitbake_source:
    default: 'source'
  repo_release:
    default: 'scarthgap'
  s3_storage:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Print environment
      shell: bash
      run:  |
        echo "Environment:"
        echo "======================================================================"
        echo "BITBAKE_BUILDNAME=${{ inputs.bitbake_buildname }}"
        echo "BITBAKE_MACHINE=${{ inputs.bitbake_machine }}"
        echo "BITBAKE_PREFIX=${{ inputs.bitbake_prefix }}"
        echo "BITBAKE_SOURCE=${{ inputs.bitbake_source }}"
        echo "BITBAKE_TARGET=${{ inputs.bitbake_target }}"
        echo "RELEASE=${{ inputs.repo_release }}"
        echo "======================================================================"
    - name: Download timestamp artifact
      uses: actions/download-artifact@v4
      with:
        pattern: timestamp.txt
        merge-multiple: true
    - name: Get timestamp prefix
      id: timestamp
      shell: bash
      run: |
        TIMESTAMP=$(cat timestamp.txt)
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
    - name: Clean the build dir
      shell: bash
      run:  |
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}.tar
    - name: Download workdir artifact
      uses: actions/download-artifact@v4
      with:
        name: yocto-meta-wpe-image-${{ inputs.repo_release }}
        path:  ~/
    - name: Untar workdir
      shell: bash
      run:  |
        cd ~
        tar -xf yocto-meta-wpe-image-${{ inputs.repo_release }}.tar
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}.tar
    - name: Install Required Packages
      shell: bash
      run:  |
        sudo apt-get install -y build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping libacl1 liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd
        sudo sh -c 'echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen'
sudo locale-gen
    - name: Build
      shell: bash
      run:  |
        cd ~/yocto-meta-wpe-image-${{ inputs.repo_release }}
        mkdir ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/builds/
        cp /local-host.conf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/builds/ || true
        ulimit -n 4096
        source sources/meta-wpe-image/scripts/setup-environment ${{ inputs.bitbake_buildname}} ${{ inputs.bitbake_machine }} ${{ inputs.bitbake_source }}
        MAX_RETRIES=5
        export ${{ inputs.bitbake_prefix }}
        for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i to fetch sources for $IMAGE..."
            if bitbake ${{ inputs.bitbake_target }} --runall=fetch; then
                echo "All sources fetched successfully."
                break
            fi

            if [ $i -lt $MAX_RETRIES ]; then
                echo "Retrying fetch process..."
            else
                echo "Max retries reached. Some sources may still be missing."
            fi
        done
        buildhistory-collect-srcrevs -a > srcrev_${{ inputs.bitbake_target }}_${{ inputs.bitbake_machine }}.inc
        diff -u ../../../conf/include/srcrev.inc srcrev_${{ inputs.bitbake_target }}_${{ inputs.bitbake_machine }}.inc ||  true
    - name: Upload buildhistory-collect-srcrevs.inc artifact
      uses: actions/upload-artifact@v4
      with:
        name: srcrev_${{ inputs.bitbake_target }}_${{ inputs.bitbake_machine }}.inc
        path: srcrev_${{ inputs.bitbake_target }}_${{ inputs.bitbake_machine }}.inc
    - name: Clean the tmp dir
      if: always()
      shell: bash
      run:  |
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/builds/${{ inputs.bitbake_buildname }}/tmp
