#! /bin/sh

# export WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1
# export GST_PLUGIN_FEATURE_RANK="avdec_av1:0"
# export GST_DEBUG_DUMP_DOT_DIR=/tmp/gst-out/
# mkdir -p /tmp/gst-out
# chmod 777 /tmp/gst-out

CTL_FILE=/tmp/wpe-exported-wayland

# WebKitDMABufVideoSink sink that is able to accept decode
# dmabuf or raw data in a range of RGB-like or YUV formats.
# Bug: https://bugs.webkit.org/show_bug.cgi?id=279819
export WEBKIT_GST_DMABUF_SINK_ENABLED=1

export GST_PLUGIN_FEATURE_RANK="avdec_av1:0"

export "$(strings < /proc/"$(pidof weston-keyboard)"/environ | grep WAYLAND_DISPLAY)"
export "$(strings < /proc/"$(pidof weston-keyboard)"/environ | grep XDG_RUNTIME_DIR)"

for arg in "$@"; do
    if [ "$arg" = "--maximized" ]; then
        echo "maximized" > ${CTL_FILE}
    fi
done

if [ "root" = "$(whoami)" ]; then
    su weston -c "/usr/bin/wpe-simple-launcher ${CTL_FILE}"
else
    /usr/bin/wpe-simple-launcher "${CTL_FILE}"
fi

echo "${arg}" > ${CTL_FILE}
