inputs:
  bitbake_prefix:
    default: ''
  bitbake_target:
    default: 'core-image-weston-wpe'
  bitbake_source:
    default: 'source'
  repo_release:
    default: 'kirkstone'
runs:
  using: 'composite'
  steps:
    - name: Print environment
      shell: bash
      run:  |
        echo "Environment:"
        echo "======================================================================"
        echo "BITBAKE_PREFIX=${{ inputs.bitbake_prefix }}"
        echo "BITBAKE_SOURCE=${{ inputs.bitbake_source }}"
        echo "BITBAKE_TARGET=${{ inputs.bitbake_target }}"
        echo "RELEASE=${{ inputs.repo_release }}"
        echo "======================================================================"
    - name: Build
      shell: bash
      run:  |
        cd ~/yocto-meta-wpe-image-${{ inputs.repo_release }}
        rm -rf tmp
        ulimit -n 4096
        #source sources/meta-wpe-image/scripts/setup-environment ${{ inputs.bitbake_source }}
        source setup-environment ${{ inputs.bitbake_source }}
        ${{ inputs.bitbake_prefix }} bitbake ${{ inputs.bitbake_target }}
    - name: Artifacts
      if: always()
      shell: bash
      run:  |
        ls -lh ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/builds/*/tmp/deploy/images/*/
    - name: Clean the tmp dir
      if: always()
      shell: bash
      run:  |
        rm -rf ~/yocto-meta-wpe-image-${{ inputs.repo_release }}/builds/*/tmp
