inputs:
  machine:
    default: 'raspberrypi5'
  repo_url:
    default: https://github.com/${{ github.repository }}.git
  repo_ref:
    default: ${{ github.ref }}
  repo_release:
    default: 'scarthgap'
  wpe_version:
    default: 'nightly'

runs:
  using: 'composite'
  steps:
    - name: Print environment
      shell: bash
      run:  |
        echo "Environment:"
        echo "======================================================================"
        echo "CI_REPOSITORY_URL=${{ inputs.repo_url }}"
        echo "CI_COMMIT_SHA=${{ inputs.repo_ref }}"
        echo "MACHINE=${{ inputs.machine }}"
        echo "RELEASE=${{ inputs.repo_release }}"
        echo "WPE_VERSION=${{ inputs.wpe_version }}"
        echo "======================================================================"
    - name: Set bitbake environment
      shell: bash
      run:  |
        sudo apt-get install -y git git-lfs pip
        export PATH=$PATH:~/.local/bin
        pip install kas

        git config --global user.email "meta-wpe-image-bot@igalia.com"
        git config --global user.name "meta-wpe-image CI Bot"
        git clone ${{ inputs.repo_url }} ~/yocto-meta-wpe-image-${{ inputs.repo_release }}
        cd ~/yocto-meta-wpe-image-${{ inputs.repo_release }}

        git remote remove tmp || true
        git remote add tmp ${{ inputs.repo_url }}
        git fetch tmp main
        git fetch tmp ${{ inputs.repo_ref }}:${{ inputs.repo_ref }}
        git checkout ${{ inputs.repo_ref }}
        git rebase tmp/main

        export KAS_CLONE_DEPTH="1"
        export KAS_WORK_DIR="workdir"
        mkdir "${KAS_WORK_DIR}"

        attempt=0
        until kas checkout kas.yml:kas/machines/${{ inputs.machine }}.yml:kas/presets/wpe-${{ inputs.wpe_version }}.yml; do
          attempt=$((attempt+1))
          if [ $attempt -ge 5 ]; then
            echo "kas checkout failed after 5 attempts. Exiting."
            exit 1
          fi
          echo "kas checkout failed. Retrying in 30 seconds... ($attempt/5)"
          sleep 30
        done
    - name: Tar workdir
      shell: bash
      run:  |
        cd ~
        tar -cf yocto-meta-wpe-image-${{ inputs.repo_release }}.tar yocto-meta-wpe-image-${{ inputs.repo_release }}
    - name: Upload tar workdir artifact
      uses: actions/upload-artifact@v4
      with:
        name: yocto-meta-wpe-image-${{ inputs.repo_release }}-${{ inputs.machine }}-${{ inputs.wpe_version }}
        path:  ~/yocto-meta-wpe-image-${{ inputs.repo_release }}.tar

