*** Variables ***
${MOTIONMARK_MIN_SCORE}      90

${VIDEO_30_FPS_THRESHOLD_CPU_LOAD}    3
${VIDEO_30_FPS_THRESHOLD_MEMORY_USED}    850
${VIDEO_30_FPS_THRESHOLD_FPS}    28

${CANVAS_FPS_THRESHOLD_CPU_LOAD}    1.2
${CANVAS_FPS_THRESHOLD_MEMORY_USED}    650
${CANVAS_FPS_THRESHOLD_FPS}    59
${CANVAS_FPS_THRESHOLD_AVERAGE}    16
${CANVAS_FPS_THRESHOLD_STD_DEVIATION}    1
