version: '3'
services:
  webserver:
    image: docker.io/library/nginx:latest
    network_mode: host
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./robot_framework/html:/robot_framework/html
      - ./tests_results:/tests_results
  robot:
    build: docker/robot/
    network_mode: host
    volumes:
      - .:/app
