#!/bin/sh
export $(cat /proc/$(pidof weston-keyboard)/environ  | strings | grep WAYLAND_DISPLAY)
export $(cat /proc/$(pidof weston-keyboard)/environ  | strings | grep XDG_RUNTIME_DIR)

if [[ "root" = "$(whoami)" ]]
then
    su weston /usr/bin/cog-fdo $1
else
    /usr/bin/cog-fdo $1
fi

