#!/bin/sh

export "$(strings < /proc/"$(pidof weston-keyboard)"/environ | grep WAYLAND_DISPLAY)"
export "$(strings < /proc/"$(pidof weston-keyboard)"/environ | grep XDG_RUNTIME_DIR)"

if [ "root" = "$(whoami)" ]
then
    su weston -c "/usr/bin/cog-fdo $*"
else
    /usr/bin/cog-fdo "$@"
fi

