#! /bin/bash

B=$1
SRC="${BUILDDIR}/../../sources"

pushd "${SRC}" || exit 1

for i in *; do
    if [ -d "$i" ]; then
        echo -e "\n>>> $i <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
        pushd "$i" > /dev/null 2>&1 || exit 1
        git fetch -a
        git checkout "$B"
        popd > /dev/null 2>&1 || exit 1
    fi
done

popd || exit 1
