runs:
  using: 'composite'
  steps:
    - name: Generate timestamped prefix
      id: timestamp
      shell: bash
      run: |
        TIMESTAMP=$(date +"%Y%m%d%H%M")
        echo ${TIMESTAMP} > timestamp.txt
    - name: Upload timestamp prefix artifact
      uses: actions/upload-artifact@v4
      with:
        name: timestamp.txt
        path: timestamp.txt
