name: Pull WebKit Git local repo

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-git-webkit:
    runs-on: [self-hosted, builder]
    strategy:
      matrix:
        runner: [builder, wk-contrib-gh-actions]
    steps:
      - name: Update local Git repo
        run: |
          cd ~/git/WebKit
          git fetch --all
          git checkout main
          git pull
          echo "::notice:: $(git log --pretty=format:'%H %s' -1)"

