name: Build tests Pull Request
on: [pull_request]
jobs:
  scarthgap-repo:
    runs-on: [self-hosted, builder]
    if: "!contains(github.event.head_commit.message, 'ci skip') && github.event_name == 'pull_request'"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'scarthgap'

  build-raspberrypi5-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi5']
        wpe_vers: ['2_46']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, builder]
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.raspberrypi conf.wpe-${{ matrix.wpe_vers }} --update-config'
          repo_release: ${{ matrix.yocto_rel }}

  test-raspberrypi5-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi5']
        wpe_vers: ['2_46']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, podman]
    permissions:
      pull-requests: write
    needs: build-raspberrypi5-stable
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/podman-robot
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          github_token: ${GITHUB_TOKEN}

  build-raspberrypi-rest-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi3-mesa', 'raspberrypi4-64-mesa']
        wpe_vers: ['2_46']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, builder]
    if: "!contains(github.event.head_commit.message, 'ci skip') && github.event_name == 'pull_request' && !github.event.pull_request.draft"
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.raspberrypi conf.wpe-${{ matrix.wpe_vers }} --update-config'
          repo_release: ${{ matrix.yocto_rel }}

  test-raspberrypi-rest-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi3-mesa']
        wpe_vers: ['2_46']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, podman]
    permissions:
      pull-requests: write
    needs: build-raspberrypi-rest-stable
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/podman-robot
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          github_token: ${GITHUB_TOKEN}

  build-freescale-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['wandboard-mesa']
        wpe_vers: ['2_46']
        yocto_rel: ['scarthgap']
    continue-on-error: true
    runs-on: [self-hosted, builder]
    if: "!contains(github.event.head_commit.message, 'ci skip') && github.event_name == 'pull_request' && !github.event.pull_request.draft"
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.freescale conf.wpe-${{ matrix.wpe_vers }} --update-config'
          repo_release: ${{ matrix.yocto_rel }}

  test-freescale-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['wandboard-mesa']
        wpe_vers: ['2_46']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, podman]
    permissions:
      pull-requests: write
    needs: build-freescale-stable
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/podman-robot
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          github_token: ${GITHUB_TOKEN}
