name: Build tests Pull Request
on: [pull_request]
jobs:
  scarthgap-repo:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'ci skip') && github.event_name == 'pull_request'"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'scarthgap'

  build-raspberrypi5-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi5']
        wpe_vers: ['2_48']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, builder]
    environment: Build Env
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.raspberrypi conf.wpe-${{ matrix.wpe_vers }} --update-config'
          repo_release: ${{ matrix.yocto_rel }}

  build-raspberrypi-rest-stable:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi4-64-mesa']
        wpe_vers: ['2_48']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, builder]
    if: "!contains(github.event.head_commit.message, 'ci skip') && github.event_name == 'pull_request'"
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/bitbake-build
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.raspberrypi conf.wpe-${{ matrix.wpe_vers }} --update-config'
          repo_release: ${{ matrix.yocto_rel }}

